services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.1.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
#      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - /disk3/eric/dataset_graph/neo4j_server/data:/data
      - /disk3/eric/dataset_graph/neo4j_server/logs:/logs
      - /disk3/eric/dataset_graph/neo4j_server/import:/var/lib/neo4j/import
      - /disk3/eric/dataset_graph/neo4j_server/plugins:/plugins